### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by sadrasabouri** [sepandhaghighi/art#107]
Can we add Github actions to this repository so that the tasks about deploying packages and releases new packages can be much more easier?

**Comment by sepandhaghighi** [comment]
Good idea!
I will work on it ;-)

**Comment by sadrasabouri** [comment]
https://github.com/sepandhaghighi/art/actions

**Comment by sadrasabouri** [comment]
https://github.blog/2020-02-27-were-challenging-you-to-create-your-very-own-github-actions/?utm_campaign=1582834318&utm_medium=social&utm_source=linkedin&utm_content=1582834318
