### ISSUE TITLE
art not printing ASCII text when compiled using pyinstaller

### ISSUE THREAD

**Issue by MrDebugger** [sepandhaghighi/art#108]
#### Description
When Python Code converted into Binary using Pyinstaller, It doesn't print ASCII text into Console anymore.

#### Steps/Code to Reproduce
1. Install `art` and `pyisntaller` using pip
2. create a simple Program such as
```
from art import *
tprint("Test",font="univers")
```
3. compile it using pyinstaller. `pyinstaller --onefile test.py`
4. open it.

#### Expected Behavior
Should print ASCII text into Console

#### Actual Behavior
Not Printing Any text into Console

#### Operating System
Windows 10

#### Python Version
3.7.4

#### ART Version
4.5

**Comment by sepandhaghighi** [comment]
@MrDebugger Hi
I repeated your reproduction steps and it seems there is no problem related to **art** library.

Put `a = input()` at the end of your script.

**Comment by MrDebugger** [comment]
> @MrDebugger Hi
> I repeated your reproduction steps and it seems there is no problem related to **art** library.
> 
> Put `a = input()` at the end of your script.

Looks Like i was editing another duplicate file and tried that on PyInstaller.
Thanks for the Reply.
