### ISSUE TITLE
How do I get the font type for each randomly generated image.

### ISSUE THREAD

**Issue by 99Kies** [sepandhaghighi/art#124]
#### Description
How do I get the font type for each randomly generated image.
#### Steps/Code to Reproduce
tprint('openhackathon', font='random')

**Comment by sadrasabouri** [comment]
Thank you for opening this issue :+1: 
I think it may bother users who don't care about the font name but as you said it might be useful if we add a flag to `tprint` function which is use for the case we want to know about font name.
`show_font_name` is my preferred bool flag name and it may works like this:

```
>>> tprint('openhackathon', font='random', show_font_name=True)
#font name : ...
openhackathon
```
What do you think @sepandhaghighi ?
Do you want to handle this issue @99Kies ?

**Comment by 99Kies** [comment]
> Thank you for opening this issue 👍
> I think it may bother users who don't care about the font name but as you said it might be useful if we add a flag to `tprint` function which is use for the case we want to know about font name.
> `show_font_name` is my preferred bool flag name and it may works like this:
> 
> ```
> >>> tprint('openhackathon', font='random', show_font_name=True)
> #font name : ...
> openhackathon
> ```
> 
> What do you think @sepandhaghighi ?
> Do you want to handle this issue @99Kies ?

Yes, it would be nice to have this as an option, which is very convenient for me to find my favorite **"font"** in **"random"**.

**Comment by 99Kies** [comment]
let me try

**Comment by sepandhaghighi** [comment]
@sadrasabouri Hi
I never thought anyone request this :D
But there is no problem, LGTM ;-)

**Comment by sepandhaghighi** [comment]
> yes, let me try
> #125

@99Kies 
Thanks for your contributing 🥇 
I review your PR and leave some comments there.
This feature implementation is straight forward

Best Regards
Sepand Haghighi

**Comment by sadrasabouri** [comment]
Hi @99Kies
You can test bellow script to find out which font best suits you: (change **k** to find more fonts)
```
>>> from art import *
>>> import random
>>> random_fonts = random.choices(FONT_NAMES, k=10)
>>> for font in random_fonts:
...     print("Font: {}".format(font))
...     tprint("Your test text!", font=font)
...     print('-' * 20)
```

Thanks for your issue and efforts for the pull request.
We decided not to implement this feature because it seems a little bit out of the `art` library goals.
So I'm going to close this issue after version `5.3` release.

**Comment by pbldmngz** [comment]
Hi, I just got here searching for the font names but they don't seem to be on the readme. There are many fonts in random but I only found wizard as an option. BTW it seems that 
```
tprint("SAMPLE", font="magic")
tprint("TEXT", font="wiz")
```
is actually random too.

**Comment by sepandhaghighi** [comment]
> Hi, I just got here searching for the font names but they don't seem to be on the readme. There are many fonts in random but I only found wizard as an option. BTW it seems that
> 
> ```
> tprint("SAMPLE", font="magic")
> tprint("TEXT", font="wiz")
> ```
> 
> is actually random too.

@pbldmngz 
Here you can take a look at all fonts that are supported by art : [Font List](https://www.4r7.ir/FontList.html)

About `wiz`, `magic` and `wizard` (they are the same) :
This mode is also random but considers the length of input text to select a font.
