### ISSUE TITLE
utf-8 characters like Chinese cannot show.

### ISSUE THREAD

**Issue by tisttsf** [sepandhaghighi/art#148]
#### Description
I want to show some Chinese in ascii art,but it didn't work.Is there a way to support that?Thanks!
```python
from art import *
art_1=art("你好hello") # return art as str in normal mode
print(art_1)
```
It cannot be show ascii draw correctly.

**Comment by sepandhaghighi** [comment]
@tisttsf Would you please give us more information about this issue?

**Comment by tisttsf** [comment]
> @tisttsf Would you please give us more information about this issue?
Sry,I did't want to open an issue,but clicked the wrong button.I wanted to search something like how to show Chinese or other format of language in ascii picture.

**Comment by tisttsf** [comment]
> @tisttsf Would you please give us more information about this issue?
I edit the issue.Is there a way to show Chinese ascii picture?

**Comment by sepandhaghighi** [comment]
@tisttsf Thanks for your comments 💯 
But we don't have any plans for this work, at least in the near future
