### ISSUE TITLE
fancytextpro.com

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/art#151]
https://www.fancytextpro.com/

_Originally posted by @sepandhaghighi in https://github.com/sepandhaghighi/art/issues/59#issuecomment-769326708_

**Comment by li71111111** [comment]
[Freaky-fonts.com](http://freaky-fonts.com/) is a free tool for generating freaky fonts. It has a comprehensive collection of freaky fonts. Users only need to type, copy, or paste, and they can transform ordinary characters into eye-catching ones, which can then be sent to Facebook, Instagram, WhatsApp, and Twitter.

<img width="1119" alt="Image" src="https://github.com/user-attachments/assets/8817a6ff-e740-417f-a46b-c99c05963e87" />

<img width="765" alt="Image" src="https://github.com/user-attachments/assets/347ac70a-ff62-45d6-9d04-32eea2525162" />

<img width="1117" alt="Image" src="https://github.com/user-attachments/assets/9aad6f45-a164-47cd-b3ae-fc0d95ce943b" [/>[](url)](url)
