### ISSUE TITLE
Wrong CRLF / LF characters for the platform

### ISSUE THREAD

**Issue by blane-nelson** [sepandhaghighi/art#161]
I really like your library.  I have a couple of use cases where I write out files on different platforms (Win/Linux) and found this issue.

The if statement is backwards, is should be ` if "win32" == sys.platform: `  for \r\n on Windows and \n on Linux.

https://github.com/sepandhaghighi/art/blob/367f50b5d0db2eecd10315c422702de0bdf2e4aa/art/art.py#L426-L428

A better way to write this would be to use the os.linesep property and remove the `if` statement.

```python
...
splitter = os.linesep
...
```
This changes doesn't look like this will break anything and would use the correct CRLF/LF.  I can submit a PR if this looks correct.
Thanks

**Comment by sepandhaghighi** [comment]
@blane-nelson Hi
Thanks for your comment 💯 
We did this because files generate in Linux based server doesn't work on Windows-based clients.
Would you please give us a reproducible report (like the issue template)?

**Comment by blane-nelson** [comment]
That would mean that the code is assuming that any files generated on Linux are to be viewed or used on Windows, which may not necessarily be the case as not all applications know how to handled the different combinations especially if the file/data ends up with mixed set of line separators. 

Here is the issue template.

#### Description
Generating Art strings on a Linux platform produces a string with "\r\n" for the line separator.

#### Steps/Code to Reproduce
```python
import art

word_art = art.text2art("Worlds of Wonder")
with open( "sample.txt", "w") as file:
    file.write("\n")
    file.writelines(title)
    file.write("\n")
    file.write("Add my text to the file\n")
    file.write("\n")
```
If you run this code on Linux and examine the raw file (hex) you will see a mixed set of \x0D0A and \x0A line for the line separators.  If executed on Windows the output will have consistent \x0D0A line separator.  The output stream will translate the \n character correctly for the platform being executed on for the write() and writelines() methods, but in this case ignores the art string because it already has the separators included and assumes that is what the caller intended.

#### Expected Behavior
My expectation is that the text2art method would use the default line separator for the platform being executed on.  Or use the \n character and allow the caller, the stream processing, or other APIs to handle translation for Windows platform, Or provide an option to set the behavior of which line separator to use for the caller's specific use case.

#### Actual Behavior
Injects the \x0D0A line terminator on Linux platform.

#### Operating System
Windows 10 Pro,  Build 19043.964
Linux, Ubuntu 20.04

#### Python Version
Windows: Python version 3.7.6
Linux: Python version 3.8.5

#### ART Version (Use : `art.__version__`)
Art version 5.1

Temporary workaround is to replace the \r\n with the platform specific line separator `title = art.text2art("Worlds of Wonder").replace("\r\n", os.linesep)`
