### ISSUE TITLE
Use lower version of setuptools to enable usage of pex

### ISSUE THREAD

**Issue by Poojith** [sepandhaghighi/art#18]
I don't evidently see the reason why the package would need a higher version of setuptools (>=39.2.0). This prevents the usage of **pex**, which has a requirement of `setuptools>=20.3,<34.0`. 
As pex is widely used, it would perhaps be feasible to disable the constraint of enforcing a higher version of setuptools.

**Comment by sepandhaghighi** [comment]
@Poojith Thanks ;-)
You are right, it will be fixed in next release.
