### ISSUE TITLE
adding colors 

### ISSUE THREAD

**Issue by codewithnick** [sepandhaghighi/art#242]
#### Description

Could not find anything related to changing color to print in the terminal, especially for printing ascii letters,
if this feature is not available then it would be good to add it?

**Comment by sepandhaghighi** [comment]
@codewithnick Hi
Thanks for your comment 💯 
Text coloring in the terminal is a bit hacky! Some interesting libraries like [termcolor](https://github.com/termcolor/termcolor) work on it. So it's not necessary for art to support it directly.

```pycon
>>> from termcolor import colored, cprint
>>> from art import text2art
>>> cprint(text2art("test"), "red")
```

@sadrasabouri What do you think?

**Comment by sadrasabouri** [comment]
> @codewithnick Hi Thanks for your comment 💯 Text coloring in the terminal is a bit hacky! Some interesting libraries like [termcolor](https://github.com/termcolor/termcolor) work on it. So it's not necessary for art to support it directly.
> 
> ```
> >>> from termcolor import colored, cprint
> >>> from art import text2art
> >>> cprint(text2art("test"), "red")
> ```
> 
> @sadrasabouri What do you think?

You're right. It's better for packages to be atomic. I prefer `art` sticks to its main goal.

**Comment by codewithnick** [comment]
I want to make a contribution to this repository do you have any ideas. I thought this was missing so bought it up.

**Comment by sadrasabouri** [comment]
@codewithnick you can start working on [this](https://github.com/sepandhaghighi/art/issues/241) issue.
Before starting anything please read [the contribution guidelines](https://github.com/sepandhaghighi/art/blob/master/.github/CONTRIBUTING.md).

PS: For getting an about how you should solve that issue, you may need to take a look at [this](https://github.com/sepandhaghighi/art/blob/master/.github/CONTRIBUTING.md) PR after skimming the source code one. Ask your probable question at the #241 issue tracker and we will respond ASAP.
