### ISSUE TITLE
font_size_splitter bug

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/art#257]
#### Description
The `font_size_splitter` function cannot be reproduced.

#### Steps/Code to Reproduce
```pycon
>>> from art import *
>>> import random
>>> random.seed(200)
>>> tprint("test", "random-large")
```
#### Expected Behavior
The output remains the same in each session (within the same version)
#### Actual Behavior
Different outputs
#### Operating System
Windows 10
#### Python Version
Python 3.8
#### ART Version (Use : `art.__version__`)
ART 6.0

**Comment by sepandhaghighi** [comment]
Sometimes, this problem can result in test failures.
We should sort `fonts` variable:
https://github.com/sepandhaghighi/art/blob/5be3f0de5c0474607a6bef28a00831c536468886/art/art.py#L27

**Comment by sepandhaghighi** [comment]
@sadrasabouri Are you interested in handling this issue?

**Comment by sadrasabouri** [comment]
Yeah sure.
