### ISSUE TITLE
sprezzkeyboard.com

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/art#74]
https://www.sprezzkeyboard.com/

_Originally posted by @sepandhaghighi in https://github.com/sepandhaghighi/art/issues/59#issuecomment-544851822_

**Comment by sepandhaghighi** [comment]
@sadrasabouri 
Would you please take a look at this website?

**Comment by sadrasabouri** [comment]
> @sadrasabouri
> Would you please take a look at this website?

Ok!
I'll look at it and add new fonts :smile:

**Comment by sepandhaghighi** [comment]
> > @sadrasabouri
> > Would you please take a look at this website?
> 
> Ok!
> I'll look at it and add new fonts 😄

Thanks ;-)
If you deal with multi-part fonts, inform me, I will add those fonts.

**Comment by sepandhaghighi** [comment]
@sadrasabouri  
Do you have any plan for this issue ?
Just a friendly reminder! ⏲

**Comment by sepandhaghighi** [comment]
I will handle this issue ;-)

**Comment by sadrasabouri** [comment]
> I will handle this issue ;-)

Thank you Sepand

**Comment by sepandhaghighi** [comment]
fixed
