### ISSUE TITLE
Add text-decoration

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/art#75]
#### Description
Add `decoration` parameter to `text2art`, `tsave` and `tprint` functions
* Default value : `None`
* Example 1 : https://g02.ir/0T9nf
* Example 2 : https://g02.ir/ZnLXO
#### Expected Behavior
```pycon
>>> from art import *
>>> tprint("test",font="fancy6",decoration="1")
▁ ▂ ▄ ▅ ▆ ▇ █ᏖᏋᏕᏖ█ ▇ ▆ ▅ ▄ ▂ ▁

```

**Comment by sadrasabouri** [comment]
Should it be indexed by number? or we can make some meaningful strings for `decoration`s?

**Comment by sepandhaghighi** [comment]
> Should it be indexed by number? or we can make some meaningful strings for `decoration`s?

Most of the websites call them `wave`, `design` and `emoticon` we can use these names, for example `wave1`,`wave2` and ...

**Comment by sadrasabouri** [comment]
I want to add `SYMETRIC_DECORATION_MAP` dictionary to `art_param` containing decoration names as keys and decoration symetric strings defined in `text_dic3.py`.
Is there any better way to do that?

**Comment by sepandhaghighi** [comment]
> I want to add `SYMETRIC_DECORATIONS_MAP` dictionary to `art_param` containing decoration names as keys and decoration symetric strings (defined in `text_dic3.py`) as values.
> Is there any better way to do that?

Good idea ;-)

My suggestions :

1. Add decorations data to a new file, like `decor_dic.py`
2. Typo-tolerance should apply for this feature

**Comment by sepandhaghighi** [comment]
@sadrasabouri  
Do you have any plan for this issue ?
Just a friendly reminder! ⏲

**Comment by sepandhaghighi** [comment]
fixed
